In [2]:
#import the libraries
import pandas as pd
import scipy
import numpy as np
from scipy import stats

# Super Market example

In [3]:
import numpy as np
t=(130-120)/(40/(np.sqrt(80)))
t

np.float64(2.23606797749979)

In [4]:
from scipy import stats
stats.t.ppf(0.975,79)

np.float64(1.9904502102301282)

In [5]:
#Conclusion:
#since tcal > tcrit , We reject null hyp, i.e., accept alt hypotheis.
#Hence it is evident that on an average the customers are spending more than $120 per week

In [6]:
stats.t.ppf(0.975,79)

np.float64(1.9904502102301282)

# Call Center example

In [7]:
import numpy as np
(4.6-4)/(3/np.sqrt(50))

np.float64(1.4142135623730943)

In [8]:
from scipy import stats
stats.norm.ppf(0.975)

np.float64(1.959963984540054)

In [9]:
2*stats.norm.cdf(-3.5)

np.float64(0.00046525815807105003)

# One tail test

In [10]:
import pandas as pd
data=pd.Series([0.593, 0.142, 0.329, 0.691, 0.231, 0.793, 0.519, 0.392, 0.418])

In [11]:
stats.ttest_1samp(data,0.3)

TtestResult(statistic=np.float64(2.2050588385131595), pvalue=np.float64(0.05853032968489765), df=np.int64(8))

In [12]:
#This gives two tail test p value so divide by 2 to get final p-value
from scipy import stats
p=stats.ttest_1samp(data,0.3)[1]
p_value= p/2
p_value

np.float64(0.029265164842448826)

In [13]:
data2=pd.Series([70,84,96,63,50,89,92,65,70,80])
stats.ttest_1samp(data2,80)

TtestResult(statistic=np.float64(-0.8824292337730089), pvalue=np.float64(0.4004992968146376), df=np.int64(9))

In [14]:
p=stats.ttest_1samp(data2,80)[1]
p/2

np.float64(0.2002496484073188)

# Two Tail test

In [15]:
import pandas as pd
Control=pd.Series([91, 87, 99, 77, 88, 91])
Treat =pd.Series([101, 110, 103, 93, 99, 104])


In [16]:
import scipy.stats as stats
stats.ttest_ind(Control,Treat)

TtestResult(statistic=np.float64(-3.4456126735364876), pvalue=np.float64(0.006272124350809803), df=np.float64(10.0))

In [17]:
stats.t.ppf(0.975,10)

np.float64(2.2281388519649385)

# 2 Proportion Test

In [18]:
import numpy as np

In [19]:
#Data:

n1 = 247
p1 = 0.37

n2 = 308
p2 = 0.39

In [20]:
population1 = np.random.binomial(1, p1, n1)
population2 = np.random.binomial(1, p2, n2)

In [21]:
population1

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0])

In [22]:
population2

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,

In [23]:
from scipy import stats
stats.ttest_ind(population1, population2)

TtestResult(statistic=np.float64(-0.6451143644064039), pvalue=np.float64(0.5191206206039443), df=np.float64(553.0))

In [24]:
np.random.randint(100,10000,100)

array([1219, 3395, 1836, 7776, 1449, 4221, 3677, 5116, 3306, 4943, 2388,
       1562, 8909, 7476, 4969,  408, 6555, 4784, 4860,  331, 5500, 8413,
       7277, 3617, 1177, 2686, 4313, 8691, 8762, 7096, 7113, 9230, 2195,
       2233, 2903, 8754, 3590, 8247, 8963, 6239, 9533, 7117,  980, 5200,
       1097,  766, 5498, 7109, 5583, 4991, 7071, 2895, 5197, 7307, 6706,
       4512, 9942, 7332, 5200, 4977, 7390, 8630, 2704, 5479, 1755, 3452,
       7369, 4171, 2715, 2802, 4820, 1650, 8145, 6700, 9864, 3232, 5964,
       9435, 5461, 4142, 4797, 6219, 5830, 5005, 8423, 6798, 9211, 8105,
       4502, 2468, 5350, 5791, 6585, 1109, 4977, 1555, 5480, 4337, 9493,
       1895])

In [25]:
np.random.uniform(0,1,100)

array([0.63913961, 0.89976901, 0.968608  , 0.80482367, 0.48413565,
       0.09333781, 0.36601983, 0.40335272, 0.61470644, 0.27095648,
       0.98806457, 0.35924436, 0.99173228, 0.83145258, 0.30411291,
       0.19515256, 0.68409045, 0.5223192 , 0.94212351, 0.53506837,
       0.50941006, 0.63970817, 0.1126797 , 0.83837677, 0.33485595,
       0.7133305 , 0.16050132, 0.76522167, 0.95593624, 0.61494597,
       0.80997116, 0.17939583, 0.38298392, 0.21152657, 0.20878707,
       0.49672925, 0.82825303, 0.99791623, 0.46178521, 0.97215431,
       0.53696213, 0.09226272, 0.76236023, 0.11815057, 0.32227411,
       0.29067214, 0.72913908, 0.19989914, 0.75674483, 0.20657828,
       0.11610704, 0.02883452, 0.1074394 , 0.0669115 , 0.90032976,
       0.22546683, 0.14460747, 0.1344464 , 0.4719366 , 0.08099144,
       0.92539769, 0.18747892, 0.19778567, 0.34406122, 0.04101209,
       0.16159557, 0.83981553, 0.40917138, 0.01568394, 0.62100479,
       0.26221771, 0.45216677, 0.04787475, 0.80555748, 0.73510

In [26]:
np.random.normal(5,25,100)   #5 mean,25sd,100 samples

array([ 7.78338111e+00, -2.77103690e+01, -2.55709151e+01, -3.87779468e+01,
       -1.06574822e-01, -2.68902173e+01,  5.07783909e+01, -5.83675619e+01,
        2.06754915e+01, -1.32548847e+00, -3.24066717e+01,  6.42318092e+00,
       -1.68691552e+01,  1.09613469e+01, -1.33613428e+01,  3.25604174e+00,
        3.64064783e+01,  1.07527844e+01, -4.33068253e+00, -2.45893785e+01,
       -4.03740420e+01, -6.31038528e+00,  9.50588269e+00,  8.60835844e+00,
        2.25652876e+01,  3.51620446e+01,  3.51049984e-01,  1.43754941e+00,
       -7.43226397e+00, -7.52823113e+00, -6.75708573e+00, -1.81764601e+00,
       -1.41084099e-03,  8.88135935e+00,  1.44447395e+01,  1.92091675e+01,
       -3.34650255e+01, -6.03352176e+00, -6.39640611e+00,  5.35513850e+00,
       -2.50443879e+01, -4.46280850e+01,  4.24541548e+01,  6.22202316e+00,
        5.11044809e+00, -1.22425321e+01,  8.43605504e-01, -3.43141413e+01,
       -2.51367947e+00, -3.09406311e+01, -2.58980171e+00,  1.52664761e+01,
        7.46702370e+00,  

In [27]:
import numpy as np

z=(130-120)/(40/np.sqrt(80))

In [28]:
z

np.float64(2.23606797749979)

In [29]:
from scipy import stats
stats.norm.ppf(0.975)

np.float64(1.959963984540054)

In [30]:
stats.t.ppf(0.975,79)

np.float64(1.9904502102301282)

In [31]:
z=(4.1-4)/(3/np.sqrt(50))
z

np.float64(0.235702260395515)

In [32]:
stats.norm.ppf(0.975)

np.float64(1.959963984540054)

In [33]:
lst=[0.593, 0.142, 0.329, 0.691, 0.231, 0.793, 0.519, 0.392, 0.418]

In [34]:
import pandas as pd
df=pd.Series(lst)
df

0    0.593
1    0.142
2    0.329
3    0.691
4    0.231
5    0.793
6    0.519
7    0.392
8    0.418
dtype: float64

In [35]:
stats.ttest_1samp(df,0.3)

TtestResult(statistic=np.float64(2.2050588385131595), pvalue=np.float64(0.05853032968489765), df=np.int64(8))

In [36]:
stats.ttest_1samp(df,0.3)[1]/2


np.float64(0.029265164842448826)

In [37]:
va=[]


In [38]:
n1=247
p1=0.37


In [39]:
import numpy as np
popA=np.random.binomial(1,p1,n1)
popA

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0])

In [40]:
n2=308
p2=0.39
popB=np.random.binomial(1,p2,n2)
popB

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,

In [41]:
stats.ttest_ind(popA,popB)

TtestResult(statistic=np.float64(-1.0380479903734476), pvalue=np.float64(0.29970137876226666), df=np.float64(553.0))

In [42]:
np.random.randint(1,100,100)

array([31, 93, 74, 92, 45, 64, 53, 13, 25, 37, 66, 85,  8, 61, 90, 28, 13,
       97, 47, 23, 92, 22, 18, 96, 59, 46, 52, 59, 93, 19, 67, 42, 51, 37,
       88, 95, 12, 16, 32, 27, 56, 33, 35, 28, 73, 76, 70, 93, 65, 20, 56,
       87, 42, 74,  9,  1, 25, 16, 43, 79, 78, 59, 79, 38,  1, 11, 19,  9,
       31, 63, 26,  9, 44, 59, 18, 90, 29, 66, 47, 84, 44,  1, 97, 86, 73,
       63, 54, 68,  6,  2, 61, 43, 27, 87, 59, 73, 50, 60, 14, 61])

In [43]:
np.random.uniform(0,1,100)

array([0.55980639, 0.83643666, 0.63195083, 0.28989644, 0.51184717,
       0.97734694, 0.62908138, 0.43258333, 0.97243928, 0.76281013,
       0.96015665, 0.97032189, 0.20463045, 0.87164609, 0.93160105,
       0.99138864, 0.16716461, 0.19410225, 0.125807  , 0.70995969,
       0.34724351, 0.47402033, 0.996615  , 0.89729776, 0.23477503,
       0.35226875, 0.68748223, 0.63495822, 0.68443963, 0.39273245,
       0.0120623 , 0.22835658, 0.63168046, 0.06409246, 0.98486314,
       0.17390171, 0.34405078, 0.43734847, 0.32660029, 0.73601004,
       0.51206354, 0.12423851, 0.81937026, 0.30841991, 0.64182667,
       0.49590895, 0.80597424, 0.67592885, 0.8559638 , 0.19859238,
       0.12128839, 0.64823216, 0.56423952, 0.53036311, 0.8858068 ,
       0.92711169, 0.01552793, 0.15818084, 0.13088544, 0.07486772,
       0.37337847, 0.13419946, 0.25732631, 0.77040099, 0.31058232,
       0.05184594, 0.06012385, 0.30973145, 0.99511561, 0.30842383,
       0.96839838, 0.52351026, 0.55289889, 0.58563543, 0.90455

In [44]:
np.random.normal(30,25,100)

array([ 14.9235478 ,   3.50197482,  16.20055956,   5.23913793,
       -30.30216424,  12.86479068,  -1.80695262,  38.91802409,
        30.40529147,  59.23967234,  24.95084197, -13.50937018,
        41.40259017,   3.48850989,  26.15337925,  48.36593535,
        64.48351559,  69.33860102,  53.4199623 ,  14.26768118,
         0.80050822,  46.05947465,  31.93619447,  37.84617478,
         7.69544908,  44.93037932,  18.48979821, 114.44729205,
        -1.12786064,  27.81080882,  26.07649127,  13.55373949,
       -16.80511503,  14.24035046,  47.70096994,  -4.38997789,
        36.34249972,  61.60496642,  54.27637078,  35.54282794,
       -45.93776748,  23.90357349,  37.03486793,  53.91789359,
        35.22838835,  55.48029385,  47.04472801,   4.45238984,
        20.10752994,  21.94844837, -26.97081919,  52.02552685,
        26.01227937,  56.63140527,  40.04813585,  44.08563797,
        51.76578121,  85.85091437,   9.299588  ,  46.61217835,
        35.99904489,   2.1113124 ,  38.39578572, -25.18

In [45]:
from scipy import stats
import numpy as np

In [46]:
#H0:mu<=120, Donot launch loyalty program
#H1:mu>120, Launch loyalty program

#test: t-test

#sample study
alpha= 0.05
n=80
x_bar=130
s=40
mu=120

#t-calculation
z_cal=(x_bar-mu)/(s/np.sqrt(n))
z_cal

np.float64(2.23606797749979)

In [47]:
z_crit=stats.norm.ppf(1-(alpha/2))
z_crit

np.float64(1.959963984540054)

In [48]:
stats.t.ppf(1-alpha/2,n-1)

np.float64(1.9904502102301282)

In [49]:
#Conclusion: since t_cal>t_crit, we reject HO
#i.e., on an average the customers are spending more than 120$ per week, hence the shopkeeper
#may launch the loyalty program

In [50]:

if t_cal<=t_crit:
  print("Accept Null Hypothesis, i.e, on an average the customers are spending less than 120$ per week, hence the shopkeeper must not launch the loyalty program")
else:
  print("Reject Null Hypothesis, i.e, on an average the customers are spending more than 120$ per week, hence the shopkeeper may launch the loyalty program")


NameError: name 't_cal' is not defined

In [ ]:
stats.norm.ppf(1-(alpha/2))

# Call center example

In [56]:
mu=4
sigma=3
n=50
x_bar=float(input("enter the sample mean:"))
alpha=0.05

#H0: mu=4, i.e., the process is normal, no action is needed
#H1: mu!=4, i.e., the process is not normal, immediate action is needed (two-tailed test)
#test: z-test, since n>30 and sigma is known

z_cal=(x_bar-mu)/(sigma/np.sqrt(n))
z_crit=stats.norm.ppf(1-alpha/2)
print(z_crit)

if np.absolute(z_cal)<=np.absolute(z_crit):
  print("Accept null hypothesis. Hence,The process is normal, no action is needed")
else:
  print("Reject null hypothesis. Hence,the process is not normal, immediate action is needed")

enter the sample mean:3.7
1.959963984540054
Accept null hypothesis. Hence,The process is normal, no action is needed


In [ ]:
np.absolute(-3.7)

#icecream factor problem

In [51]:
import pandas as pd

In [52]:
n=9
mu=0.3
alpha=0.05

#H0: mu<=0.3, the disease is not due to icecream factory, no action is needed
#H1: mu>0.3, the disease is due to the icecream factory, shut down immediately(one tailed)

data=[0.593, 0.142, 0.329, 0.691, 0.231, 0.793, 0.519, 0.392, 0.418]
stats.ttest_1samp(data,mu)

TtestResult(statistic=np.float64(2.2050588385131595), pvalue=np.float64(0.05853032968489765), df=np.int64(8))

In [53]:
p_val=stats.ttest_1samp(data,mu)[1]/2

In [54]:
if p_val<alpha:
  print("Reject Null Hypothesis,the disease is due to the icecream factory, shut down immediately")
else:
  print("Accept null hypothesis,the disease is not due to icecream factory, no action is needed ")

Reject Null Hypothesis,the disease is due to the icecream factory, shut down immediately


# Control and treatment grp problem

In [ ]:
#H0: mu1=mu2, there is no significant difference between control group and the treatment group
#H1: mu1!=mu2, there is a significant diffence between control grp and treatment group(two-tailed test)

alpha=0.05
control=[91, 87, 99, 77, 88, 91]
treat=[101, 110, 103, 93, 99, 104]

stats.ttest_ind(control,treat)

In [ ]:
p_val=stats.ttest_ind(control,treat)[1]

In [ ]:
if p_val<alpha:
  print("Reject Null Hypothesis,there is a significant diffence between control group and treatment group")
else:
  print("Accept null hypothesis,there is no significant difference between control group and the treatment group ")

#2 proportion  test

In [ ]:
#H0: P1=P2, i.e., the proportion of state 1 and state 2 student population getting placed immediately after education is same
#(or) there is no significant difference between proportion of state 1 and state 2 population getting job immediately after education

#H1: P1 != P2, i.e., the proportion of state 1 and state 2 student population getting placed immediately after education is different
#(or) there is a significant difference between proportion of state 1 and state 2 population getting job immediately after education

#test: t-test

alpha=0.05
n1=247
p1=0.37
n2=308
p2=0.39

#let us generate random data following binomial distribution for both the states
import numpy as np
pop1=np.random.binomial(1,p1,n1)
pop2=np.random.binomial(1,p2,n2)

In [ ]:
pop2

In [ ]:
import scipy.stats as st
st.ttest_ind(pop1,pop2)

In [ ]:
p_val=st.ttest_ind(pop1,pop2)[1]
if p_val<alpha:
  print("Reject Null Hypothesis,there is a significant diffence between state 1 proportion and state2 proportion")
else:
  print("Accept null hypothesis,there is no significant difference between state 1 proportion and state2 proportion")


In [ ]:
#H0: PA=PB
#H1: PB>PA

processA = [89.7, 81.4, 84.5, 84.8, 87.3, 79.7, 85.1, 81.7, 83.7, 84.5]
ProcessB = [84.7, 86.1, 83.2, 91.9, 86.3, 79.3, 82.6, 89.1, 83.7, 88.5]

# stats.ttest_ind(control,treat)
stats.ttest_ind(processA,ProcessB)